services:
  - type: web
    name: greenlens
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn greenlens.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: greenlens-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: NASA_USERNAME
        sync: false
      - key: NASA_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          name: greenlens-redis
          type: redis
          property: connectionString

  - type: worker
    name: greenlens-celery
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A greenlens worker --loglevel=info --pool=solo
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: greenlens-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: greenlens-redis
          type: redis
          property: connectionString

  - type: worker
    name: greenlens-celery-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A greenlens beat --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: greenlens-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: greenlens-redis
          type: redis
          property: connectionString

  - type: redis
    name: greenlens-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

databases:
  - name: greenlens-db
    databaseName: greenlens
    user: greenlens
    plan: free
