services:
  - type: web
    name: greenlens
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn greenlens.wsgi:application --workers 2 --timeout 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: greenlens-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: NASA_USERNAME
        sync: false
      - key: NASA_PASSWORD
        sync: false

databases:
  - name: greenlens-db
    databaseName: greenlens
    user: greenlens
    plan: free
