# Copyright (c) 2026 Sharun Tomy
# Licensed under BUSL-1.1. See LICENSE file for details.
# Commercial use prohibited without written permission.

# Generated by Django 5.0.6 on 2026-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_id', models.CharField(db_index=True, max_length=100)),
                ('error_type', models.CharField(choices=[('pcrs_wrong', 'PCRS Score Wrong'), ('gw_false_pos', 'Greenwash False Positive'), ('gw_false_neg', 'Greenwash False Negative'), ('pricing_wrong', 'Pricing Gap Wrong')], db_index=True, max_length=30)),
                ('predicted_value', models.CharField(max_length=255)),
                ('actual_value', models.CharField(max_length=255)),
                ('error_description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('potential_user_impact', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('root_cause_category', models.CharField(blank=True, choices=[('data_quality', 'Data Quality'), ('model_limitation', 'Model Limitation'), ('api_error', 'API Error'), ('edge_case', 'Edge Case'), ('unknown', 'Unknown')], max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_action', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reported_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Classification Error',
                'verbose_name_plural': 'Classification Errors',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['error_type', 'severity'], name='risk_manage_error_t_1efb73_idx'), models.Index(fields=['is_resolved'], name='risk_manage_is_reso_8cb0b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('metric_type', models.CharField(choices=[('completeness', 'Completeness'), ('accuracy', 'Accuracy'), ('consistency', 'Consistency'), ('timeliness', 'Timeliness')], max_length=50)),
                ('value', models.FloatField()),
                ('threshold_warning', models.FloatField()),
                ('threshold_critical', models.FloatField()),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('affected_records', models.IntegerField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Data Quality Metric',
                'verbose_name_plural': 'Data Quality Metrics',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['metric_name', 'measured_at'], name='risk_manage_metric__d6a3ea_idx'), models.Index(fields=['status'], name='risk_manage_status_790063_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('api_failure', 'API Failure'), ('db_error', 'Database Error'), ('model_error', 'Model Error'), ('data_error', 'Data Error'), ('infrastructure', 'Infrastructure'), ('security', 'Security')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('affected_users', models.IntegerField(default=0)),
                ('affected_bonds', models.IntegerField(default=0)),
                ('downtime_minutes', models.IntegerField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('resolution_action', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incident Log',
                'verbose_name_plural': 'Incident Logs',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['incident_type', 'status'], name='risk_manage_inciden_15d608_idx'), models.Index(fields=['detected_at'], name='risk_manage_detecte_04e913_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalRiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('investment_advice', 'Investment Advice Liability'), ('defamation', 'Defamation / False Greenwash Flag'), ('gdpr', 'GDPR / Data Privacy'), ('regulatory', 'Regulatory Compliance'), ('ip', 'Intellectual Property')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('mitigation_action', models.TextField()),
                ('mitigation_status', models.CharField(choices=[('identified', 'Identified'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved'), ('escalated', 'Escalated to Legal')], default='identified', max_length=20)),
                ('compliance_requirement', models.CharField(blank=True, max_length=255)),
                ('compliance_deadline', models.DateField(blank=True, null=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('legal_review_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Legal Risk Log',
                'verbose_name_plural': 'Legal Risk Logs',
                'ordering': ['-identified_at'],
                'indexes': [models.Index(fields=['risk_type', 'severity'], name='risk_manage_risk_ty_c7a77a_idx'), models.Index(fields=['mitigation_status'], name='risk_manage_mitigat_cc152c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelDriftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('drift_type', models.CharField(choices=[('accuracy_drop', 'Accuracy Drop'), ('prediction_shift', 'Prediction Shift'), ('feature_change', 'Feature Importance Change'), ('distribution_shift', 'Distribution Shift')], db_index=True, max_length=30)),
                ('previous_accuracy', models.FloatField()),
                ('current_accuracy', models.FloatField()),
                ('accuracy_drop_percentage', models.FloatField()),
                ('description', models.TextField()),
                ('affected_predictions', models.IntegerField(help_text='Number of predictions affected')),
                ('alert_severity', models.CharField(choices=[('warning', 'Warning'), ('alert', 'Alert'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('retraining_scheduled', models.BooleanField(default=False)),
                ('retraining_date', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Model Drift Alert',
                'verbose_name_plural': 'Model Drift Alerts',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['model_name', 'detected_at'], name='risk_manage_model_n_081737_idx'), models.Index(fields=['alert_severity'], name='risk_manage_alert_s_2a73e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemFailureScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('scenario_type', models.CharField(choices=[('api_failure', 'API Failure'), ('model_drift', 'Model Drift'), ('data_poisoning', 'Data Poisoning'), ('infrastructure', 'Infrastructure'), ('classification_error', 'Classification Error')], db_index=True, max_length=50)),
                ('probability', models.CharField(choices=[('low', 'Low (< 10%)'), ('medium', 'Medium (10-50%)'), ('high', 'High (50-90%)'), ('critical', 'Critical (> 90%)')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('impact_description', models.TextField()),
                ('affected_modules', models.JSONField(default=list, help_text="List of affected modules (e.g., ['greenwash_detector', 'risk_scoring'])")),
                ('mitigation_strategy', models.TextField()),
                ('mitigation_status', models.CharField(choices=[('identified', 'Identified'), ('mitigating', 'Mitigating'), ('mitigated', 'Mitigated'), ('monitoring', 'Monitoring')], db_index=True, default='identified', max_length=20)),
                ('has_fallback', models.BooleanField(default=False)),
                ('fallback_description', models.TextField(blank=True)),
                ('recovery_time_minutes', models.IntegerField(blank=True, help_text='Estimated recovery time in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Failure Scenario',
                'verbose_name_plural': 'System Failure Scenarios',
                'ordering': ['-severity', '-probability'],
                'indexes': [models.Index(fields=['scenario_type', 'mitigation_status'], name='risk_manage_scenari_11a08d_idx'), models.Index(fields=['severity'], name='risk_manage_severit_6238c3_idx')],
            },
        ),
    ]
