# Generated by Django 5.0.6 on 2026-04-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_spread_bps', models.FloatField(help_text='Observed yield spread over benchmark (basis points)')),
                ('predicted_spread_bps', models.FloatField(help_text='PCRS-model-implied fair-value spread (basis points)')),
                ('gap_bps', models.FloatField(help_text='Mispricing gap: actual minus predicted (basis points)')),
                ('is_mispriced', models.BooleanField(db_index=True, default=False, help_text='True when |gap_bps| exceeds the materiality threshold (±20 bps)')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_source', models.CharField(default='yahoo_finance', help_text='Source of the actual spread data', max_length=50)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_gaps', to='data_ingestion.greenbond')),
            ],
            options={
                'verbose_name': 'Pricing Gap',
                'verbose_name_plural': 'Pricing Gaps',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['bond', 'checked_at'], name='pricing_ana_bond_id_c15b4a_idx'), models.Index(fields=['is_mispriced'], name='pricing_ana_is_misp_abc8d9_idx'), models.Index(fields=['gap_bps'], name='pricing_ana_gap_bps_b9fa3c_idx')],
            },
        ),
    ]
