# Copyright (c) 2026 Sharun Tomy
# Licensed under BUSL-1.1. See LICENSE file for details.
# Commercial use prohibited without written permission.

# Generated by Django 5.0.6 on 2026-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricinggap',
            name='calculation_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date on which spread data was calculated or fetched', null=True),
        ),
        migrations.AddField(
            model_name='pricinggap',
            name='is_live',
            field=models.BooleanField(db_index=True, default=False, help_text='True when spread was fetched from a live market data source; False = synthetic estimate'),
        ),
    ]
