# Copyright (c) 2026 Sharun Tomy
# Licensed under BUSL-1.1. See LICENSE file for details.
# Commercial use prohibited without written permission.

# Generated by Django 5.0.6 on 2026-04-21 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('issuer_name', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('project_category', models.CharField(choices=[('solar', 'Solar Energy'), ('wind', 'Wind Energy'), ('water', 'Water & Sanitation'), ('transport', 'Clean Transport'), ('building', 'Green Building'), ('reforestation', 'Reforestation'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('project_description', models.TextField(blank=True)),
                ('bond_maturity_years', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('issuance_date', models.DateField(db_index=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('OTHER', 'Other')], default='USD', max_length=10)),
                ('amount_millions', models.DecimalField(decimal_places=2, help_text='Bond amount in millions of the specified currency', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('lat', models.FloatField(help_text='Latitude of the project site', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lon', models.FloatField(help_text='Longitude of the project site', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Green Bond',
                'verbose_name_plural': 'Green Bonds',
                'ordering': ['-issuance_date'],
                'indexes': [models.Index(fields=['country', 'project_category'], name='data_ingest_country_c50a88_idx'), models.Index(fields=['issuance_date'], name='data_ingest_issuanc_22acc1_idx'), models.Index(fields=['issuer_name'], name='data_ingest_issuer__199159_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClimateHazardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flood_risk_index', models.FloatField(help_text='Normalised flood risk index (0 = no risk, 1 = extreme risk)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('heat_stress_index', models.FloatField(help_text='Normalised heat stress index (0 = no stress, 1 = extreme stress)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('drought_spei', models.FloatField(help_text='Standardised Precipitation-Evapotranspiration Index. Negative = drought; positive = wet conditions.')),
                ('data_date', models.DateField(db_index=True, help_text='Date of the underlying satellite observation')),
                ('source', models.CharField(choices=[('nasa', 'NASA Earthdata'), ('esa', 'ESA Copernicus'), ('noaa', 'NOAA'), ('ipcc', 'IPCC AR6'), ('other', 'Other')], default='nasa', max_length=10)),
                ('raw_metadata', models.JSONField(blank=True, default=dict, help_text='Raw API response metadata for audit purposes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_data', to='data_ingestion.greenbond')),
            ],
            options={
                'verbose_name': 'Climate Hazard Data',
                'verbose_name_plural': 'Climate Hazard Data',
                'ordering': ['-data_date'],
                'indexes': [models.Index(fields=['bond', 'data_date'], name='data_ingest_bond_id_af788c_idx'), models.Index(fields=['data_date'], name='data_ingest_data_da_dbe872_idx')],
            },
        ),
    ]
