# Generated by Django 5.0.6 on 2026-04-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenbond',
            name='location_confidence',
            field=models.CharField(choices=[('precise', 'Precise (GPS / address-level)'), ('city', 'City-level geocoding'), ('country', 'Country centroid (fallback)')], default='country', help_text="Geocoding precision level for this bond's project coordinates", max_length=10),
        ),
    ]
