# Generated by Django 5.0.6 on 2026-04-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0002_add_location_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenbond',
            name='data_source',
            field=models.CharField(default='CBI', help_text='Registry source: CBI, IMF, Refinitiv, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='greenbond',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last data sync from the registry source', null=True),
        ),
    ]
