# Generated by Django 5.0.6 on 2026-04-26 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0003_add_sync_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatehazarddata',
            name='carbon_intensity_score',
            field=models.FloatField(blank=True, help_text='Country-level carbon intensity score (0=low, 1=high) — sourced from EDGAR CO2 data', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='climatehazarddata',
            name='policy_risk_score',
            field=models.FloatField(blank=True, help_text='Policy risk score (0=stable, 1=high risk) — World Bank Governance Indicators', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='climatehazarddata',
            name='transition_risk_score',
            field=models.FloatField(blank=True, help_text='Transition risk score (0=low, 1=high) — based on country NDC ambition and fossil fuel dependency', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
