# Copyright (c) 2026 Sharun Tomy
# Licensed under BUSL-1.1. See LICENSE file for details.
# Commercial use prohibited without written permission.

# Generated by Django 5.0.6 on 2026-04-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0010_add_spatial_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='greenbond',
            name='idx_bond_filter_combo',
        ),
        migrations.RemoveIndex(
            model_name='greenbond',
            name='idx_bond_amount',
        ),
        migrations.RemoveIndex(
            model_name='greenbond',
            name='idx_location_conf',
        ),
        migrations.RemoveIndex(
            model_name='greenbond',
            name='idx_bond_latlon',
        ),
    ]
