# Copyright (c) 2026 Sharun Tomy
# Licensed under BUSL-1.1. See LICENSE file for details.
# Commercial use prohibited without written permission.

# Generated by Django 5.0.6 on 2026-05-08 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0011_remove_greenbond_idx_bond_filter_combo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="climatehazarddata",
            name="cyclone_risk_index",
            field=models.FloatField(
                blank=True,
                help_text="India cyclone risk score (0=no risk, 1=extreme risk) — IMD historical cyclone tracks",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="climatehazarddata",
            name="heat_wave_risk_index",
            field=models.FloatField(
                blank=True,
                help_text="India heat wave risk using WBGT (0=low, 1=extreme) — IMD heat wave frequency",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="climatehazarddata",
            name="monsoon_risk_index",
            field=models.FloatField(
                blank=True,
                help_text="India monsoon risk score (0=no risk, 1=extreme risk) — IMD seasonal forecast + ENSO",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="greenbond",
            name="disclosure_quality",
            field=models.CharField(
                choices=[
                    ("HIGH", "GPS + verified"),
                    ("MEDIUM", "City level + audited"),
                    ("LOW", "State/country + self-reported"),
                ],
                default="LOW",
                help_text="Quality level of location and verification disclosure",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="greenbond",
            name="regulatory_framework",
            field=models.CharField(
                choices=[
                    ("EU_GBS", "EU Green Bond Standard"),
                    ("SEBI", "SEBI Green Bond Framework"),
                    ("CBI", "Climate Bonds Standard"),
                    ("ICMA", "ICMA Green Bond Principles"),
                    ("OTHER", "Other/Self-labeled"),
                ],
                default="OTHER",
                help_text="Regulatory framework under which the bond is issued",
                max_length=10,
            ),
        ),
    ]
