# Generated by Django 5.0.6 on 2026-04-21 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenwashFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_change', models.FloatField(help_text='Change in Normalised Difference Vegetation Index between pre- and post-project satellite imagery. Positive = greening; negative = vegetation loss.')),
                ('satellite_land_use', models.CharField(help_text="Land-use class inferred from satellite imagery (e.g. 'bare_soil', 'forest')", max_length=100)),
                ('pre_project_image_date', models.DateField(blank=True, help_text='Acquisition date of the baseline satellite image', null=True)),
                ('post_project_image_date', models.DateField(blank=True, help_text='Acquisition date of the comparison satellite image', null=True)),
                ('claimed_project_type', models.CharField(help_text='Project type as self-reported by the bond issuer', max_length=100)),
                ('is_inconsistent', models.BooleanField(db_index=True, default=False, help_text='True when satellite evidence is inconsistent with the claimed project type')),
                ('confidence', models.FloatField(help_text='Model confidence in the inconsistency classification (0–1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('model_version', models.CharField(default='v1.0.0', help_text='Version of the CNN classifier used', max_length=30)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_ee_metadata', models.JSONField(blank=True, default=dict, help_text='Raw Google Earth Engine API response for audit trail')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenwash_flags', to='data_ingestion.greenbond')),
            ],
            options={
                'verbose_name': 'Greenwash Flag',
                'verbose_name_plural': 'Greenwash Flags',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['bond', 'checked_at'], name='greenwash_d_bond_id_26f69a_idx'), models.Index(fields=['is_inconsistent'], name='greenwash_d_is_inco_93782a_idx'), models.Index(fields=['confidence'], name='greenwash_d_confide_90e4ee_idx')],
            },
        ),
    ]
