# Generated by Django 5.0.6 on 2026-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenwash_detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenwashflag',
            name='verification_status',
            field=models.CharField(choices=[('verifiable', 'Verifiable'), ('unverifiable', 'Unverifiable')], default='verifiable', help_text="Whether satellite data is available for this bond's timeline", max_length=20),
        ),
    ]
