# Generated by Django 5.0.6 on 2026-04-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ingestion', '0011_remove_greenbond_idx_bond_filter_combo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCRSSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('pcrs_score', models.FloatField()),
                ('flood_index', models.FloatField(blank=True, null=True)),
                ('heat_index', models.FloatField(blank=True, null=True)),
                ('drought_spei', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=30)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcrs_snapshots', to='data_ingestion.greenbond')),
            ],
            options={
                'verbose_name': 'PCRS Snapshot',
                'verbose_name_plural': 'PCRS Snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['bond', 'snapshot_date'], name='future_feat_bond_id_d5ea5c_idx'), models.Index(fields=['snapshot_date'], name='future_feat_snapsho_2d9f9d_idx')],
                'unique_together': {('bond', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='ProjectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(db_index=True, max_length=20)),
                ('method', models.CharField(default='SSP_LINEAR_PROJECTION', help_text='SSP_LINEAR_PROJECTION until LSTM is ready (2027 Q4)', max_length=30)),
                ('current_pcrs', models.FloatField()),
                ('projected_pcrs_5yr', models.FloatField(blank=True, null=True)),
                ('projected_pcrs_10yr', models.FloatField(blank=True, null=True)),
                ('stranded_asset_risk', models.BooleanField(default=False)),
                ('risk_crossing_year', models.IntegerField(blank=True, null=True)),
                ('trajectory_json', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='data_ingestion.greenbond')),
            ],
            options={
                'verbose_name': 'Projection Result',
                'verbose_name_plural': 'Projection Results',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['bond', 'scenario'], name='future_feat_bond_id_ab405d_idx'), models.Index(fields=['stranded_asset_risk'], name='future_feat_strande_e8ae92_idx')],
                'unique_together': {('bond', 'scenario')},
            },
        ),
    ]
