# Copyright (c) 2026 Sharun Tomy
# Licensed under BUSL-1.1. See LICENSE file for details.
# Commercial use prohibited without written permission.

# Generated by Django 5.0.6 on 2026-04-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ingestion', '0011_remove_greenbond_idx_bond_filter_combo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(choices=[('ssp1_1_9', 'SSP1-1.9 (Very Low Emissions)'), ('ssp1_2_6', 'SSP1-2.6 (Low Emissions)'), ('ssp2_4_5', 'SSP2-4.5 (Intermediate Emissions)'), ('ssp3_7_0', 'SSP3-7.0 (High Emissions)'), ('ssp5_8_5', 'SSP5-8.5 (Very High Emissions)')], db_index=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('warming_by_2050', models.FloatField(help_text='Expected warming in °C by 2050')),
                ('warming_by_2100', models.FloatField(help_text='Expected warming in °C by 2100')),
            ],
            options={
                'verbose_name': 'Climate Scenario',
                'verbose_name_plural': 'Climate Scenarios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=255)),
                ('portfolio_description', models.TextField(blank=True)),
                ('current_bonds', models.JSONField(default=list, help_text='List of current bond holdings with amounts')),
                ('current_pcrs', models.FloatField()),
                ('current_return', models.FloatField(help_text='Expected return %')),
                ('optimized_bonds', models.JSONField(default=list, help_text='List of optimized bond holdings with amounts')),
                ('optimized_pcrs', models.FloatField()),
                ('optimized_return', models.FloatField(help_text='Expected return %')),
                ('sell_recommendations', models.JSONField(default=list, help_text='Bonds to sell with reasons')),
                ('buy_recommendations', models.JSONField(default=list, help_text='Bonds to buy with reasons')),
                ('min_return_target', models.FloatField()),
                ('max_single_bond_allocation', models.FloatField(default=5.0)),
                ('geographic_diversification_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('implemented', 'Implemented')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio Optimization',
                'verbose_name_plural': 'Portfolio Optimizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ai_features_status_0bccde_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_type', models.CharField(choices=[('eu_sfdr', 'EU SFDR'), ('eu_taxonomy', 'EU Taxonomy'), ('sebi_brsr', 'SEBI BRSR'), ('rbi_climate', 'RBI Climate Risk'), ('sec_climate', 'SEC Climate Disclosure')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('announcement_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('impact_description', models.TextField()),
                ('affected_bonds_count', models.IntegerField(blank=True, null=True)),
                ('compliance_required', models.BooleanField(default=True)),
                ('action_required', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regulatory Monitor',
                'verbose_name_plural': 'Regulatory Monitors',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['regulation_type', 'effective_date'], name='ai_features_regulat_df25c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomatedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('climate_event', 'Climate Event Alert'), ('greenwash', 'Greenwash Detection Alert'), ('pricing', 'Pricing Anomaly Alert'), ('regulatory', 'Regulatory Change Alert')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alert_data', models.JSONField(default=dict, help_text='Structured alert data (event details, PCRS changes, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('dashboard', 'Dashboard'), ('sms', 'SMS'), ('webhook', 'Webhook')], default='email', max_length=50)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_minutes', models.IntegerField(blank=True, null=True)),
                ('affected_bonds', models.ManyToManyField(help_text='Bonds affected by this alert', related_name='alerts', to='data_ingestion.greenbond')),
            ],
            options={
                'verbose_name': 'Automated Alert',
                'verbose_name_plural': 'Automated Alerts',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['alert_type', 'status'], name='ai_features_alert_t_69f77c_idx'), models.Index(fields=['triggered_at'], name='ai_features_trigger_d60602_idx')],
            },
        ),
        migrations.CreateModel(
            name='PCRSPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pcrs', models.FloatField()),
                ('current_date', models.DateField()),
                ('predicted_pcrs', models.FloatField()),
                ('prediction_date', models.DateField()),
                ('confidence', models.FloatField(help_text='Confidence 0-100%')),
                ('primary_driver', models.CharField(choices=[('sea_level_rise', 'Sea Level Rise'), ('temperature_increase', 'Temperature Increase'), ('precipitation_change', 'Precipitation Change'), ('extreme_weather', 'Extreme Weather Frequency')], max_length=100)),
                ('driver_magnitude', models.FloatField(help_text='Expected change in driver (e.g., 0.3m sea level rise)')),
                ('model_version', models.CharField(default='v1.0.0', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcrs_predictions', to='data_ingestion.greenbond')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcrs_predictions', to='ai_features.climatescenario')),
            ],
            options={
                'verbose_name': 'PCRS Prediction',
                'verbose_name_plural': 'PCRS Predictions',
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['bond', 'scenario'], name='ai_features_bond_id_b115e8_idx'), models.Index(fields=['prediction_date'], name='ai_features_predict_1b80ef_idx')],
            },
        ),
    ]
