name: GreenLens CI/CD

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Code pushed successfully
        run: echo "Code pushed to main branch successfully"
