# Generated by Django 5.0.6 on 2026-04-21 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCRScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Overall Physical Climate Risk Score (0–100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('flood_contribution', models.FloatField(help_text='SHAP contribution of flood risk index to the total score')),
                ('heat_contribution', models.FloatField(help_text='SHAP contribution of heat stress index to the total score')),
                ('drought_contribution', models.FloatField(help_text='SHAP contribution of drought SPEI to the total score')),
                ('model_version', models.CharField(db_index=True, help_text='Semantic version of the XGBoost model used (e.g. v1.2.0)', max_length=30)),
                ('scored_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('shap_values', models.JSONField(blank=True, default=dict, help_text='Full SHAP values dict for all features')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcr_scores', to='data_ingestion.greenbond')),
            ],
            options={
                'verbose_name': 'PCR Score',
                'verbose_name_plural': 'PCR Scores',
                'ordering': ['-scored_at'],
                'indexes': [models.Index(fields=['bond', 'scored_at'], name='risk_scorin_bond_id_a86c13_idx'), models.Index(fields=['model_version'], name='risk_scorin_model_v_25c488_idx'), models.Index(fields=['score'], name='risk_scorin_score_8ca4e4_idx')],
            },
        ),
    ]
