# Copyright (c) 2026 Sharun Tomy
# Licensed under BUSL-1.1. See LICENSE file for details.
# Commercial use prohibited without written permission.

# Generated by Codex on 2026-04-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_scoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("decision", models.CharField(choices=[("avoid", "Avoid"), ("buy", "Buy"), ("hold", "Hold"), ("watchlist", "Watchlist"), ("sell", "Sell")], db_index=True, default="watchlist", max_length=20)),
                ("outcome", models.CharField(choices=[("pending", "Pending outcome"), ("no_loss", "No loss observed"), ("loss", "Loss observed"), ("default", "Default / distress"), ("price_recovery", "Price recovery"), ("model_error", "Model review needed")], db_index=True, default="pending", max_length=30)),
                ("pcr_score_at_decision", models.FloatField(blank=True, null=True)),
                ("pricing_gap_bps_at_decision", models.FloatField(blank=True, null=True)),
                ("location_confidence_at_decision", models.CharField(blank=True, max_length=20)),
                ("realized_loss_bps", models.FloatField(blank=True, help_text="Observed loss or underperformance in basis points, if known.", null=True)),
                ("outcome_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("used_for_retraining", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bond", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="model_feedback", to="data_ingestion.greenbond")),
                ("pcr_score", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="feedback_events", to="risk_scoring.pcrscore")),
            ],
            options={
                "verbose_name": "Model Feedback",
                "verbose_name_plural": "Model Feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["bond", "created_at"], name="risk_scorin_bond_id_74615a_idx"),
                    models.Index(fields=["outcome", "used_for_retraining"], name="risk_scorin_outcome_0f1ad1_idx"),
                ],
            },
        ),
    ]
