# Copyright (c) 2026 Sharun Tomy
# Licensed under BUSL-1.1. See LICENSE file for details.
# Commercial use prohibited without written permission.

# Generated by Django 5.0.6 on 2026-05-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk_scoring", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pcrscore",
            name="idx_pcr_score_bond",
        ),
        migrations.RemoveIndex(
            model_name="pcrscore",
            name="idx_pcr_score_only",
        ),
    ]
